### ISSUE TITLE
Admin login page Login button is disabled despite of validation rules.

### ISSUE THREAD

**Issue by nteej** [avored/laravel-ecommerce#174]
**Ideally we would expect you to raise a bug on AvoRed Official Website **
https://www.avored.com/discussion/category/general

**Describe the bug**
When trying to login to backend,Login button doesn't activate due JS error.

**To Reproduce**

**Screenshots**
![screenshot from 2018-07-01 18-24-01](https://user-images.githubusercontent.com/24771749/42134797-c7caf09c-7d5f-11e8-98a8-b287757b2990.png)

**Desktop (please complete the following information):**

**Additional context**

**Comment by indpurvesh** [comment]
Bug itself has been fixed. 

to fixed the bug follow the steps:

Open file : `modules/avored/ecommerce/resources/assets/components/forms/avored-form-input.vue`
change Line:

    onChange: function(){
    //New line
    onChange: function(**event**){


Open file : `modules/avored/ecommerce/resources/assets/components/forms/avored-form-select.vue`
change Line:

    onChange: function(){
    //New line
    onChange: function(**event**){


Open file : `modules/avored/ecommerce/resources/assets/components/forms/avored-form-textarea.vue`
change Line:

    onChange: function(){
    //New line
    onChange: function(**event**){

Once you changed in above three files: 

    npm install 
    npm run avored:admin:prod

Thanks

**Comment by nteej** [comment]
@indpurvesh Thanks a lot.I'll get fix based on ur solution.I've created new theme with  megamenu & quick view & other stuffs.But still not finish functional part.I created it under theme avored/cartler.
Once Finish I'll commit the code.
